exclude:
    - "src/"
    - "README.md"
    - "package.json"
    - "package-lock.json"
    - "webpack.config.js"

collections:
    gallery:

sass:
    load_paths:
        - node_modules
        - assets